# Generated by Django 4.2.5 on 2023-11-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userloginApp', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='verify_otp',
        ),
    ]
